---
  - name: "Create directory"
    file:
      path: ~/be-app
      state: directory

  - name: "extract artifact"
    unarchive:
      src: artifact.tar.gz
      dest: ~/be-app
    
  - name: "install dependencies"
    shell: |
      cd ~/be-app
      npm i
      
  - name: "list"
    shell: |
      ls -a ~/be-app
      
  - name: "print"
    debug:
      msg: "TYPEORM_CONNECTION:{{ lookup('env', 'TYPEORM_CONNECTION')}}\n TYPEORM_ENTITIES:{{ lookup('env', 'TYPEORM_ENTITIES')}}"
         
  - name: "Executing with pm2"
    shell: |
       cd ~/be-app/dist
       pm2 stop default
       pm2 start main.js

  - name: "start service"
    become: true
    shell: |
      env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
